### ISSUE TITLE
xTextarea的一个问题

### ISSUE THREAD

**Issue by cody1991** [yunfeihuang/vue-components#1]
http://assets.bittyos.com/vue-components/#/textarea

这里的样式

```
&textarea-shadow{
      position:absolute;
      left:0;
      top:0;
      min-height:2.6rem;
      word-break: break-all;
      opacity:0;
      z-index: -1
}

```
不应该加的  word-break: break-all; 的，不然在 textarea 里面 和 v-textarea-shadow 里面，内容排版可能存在不一致，最后高度肯定也不一致， textarea 的展示会出现问题

**Comment by yunfeihuang** [comment]
word-break: break-all;是用处理长串英文不换行，而导致高度计算有不对。您是什么操作才会出现问题？

**Comment by yunfeihuang** [comment]
刚才自己测试发现了异常，已经修复了异常。不知道是不是你提的问题？有空验一下，蟹蟹...

**Comment by cody1991** [comment]
昨天贴图上传一直失败... 不过看你修复了

另外也看到你修改了  <slot></slot> 这个，我昨天尝试过用 <slot></slot> 填充在 textarea 里面，一直不行，然后就换成了 :content="content" 的方法，和你现在的一样处理方式

好好奇为什么你之前的代码能运行...

**Comment by yunfeihuang** [comment]
可能是环境的原因吧，我现在修改成props传值了(之前是slot)

**Comment by cody1991** [comment]
ok ~ 没问题了哈 蟹蟹

最近也在用 vue 写项目，自己写的感觉不忍直视，感觉重复的代码太多，还有组织上做的不好，刚好看到你这个项目，晚上没事就看看跟着敲着学习了

**Comment by yunfeihuang** [comment]
谦虚了，我写的也有些不好。一起多多交流
