### ISSUE TITLE
 哥们，你的new Vue动态创建的组件，为什么在2.0会爆粗，编译不过！！！

### ISSUE THREAD

**Issue by JDreamLuo** [yunfeihuang/vue-components#2]

**Comment by JDreamLuo** [comment]
怎么解决呢

**Comment by yunfeihuang** [comment]
不好意思，请把报错的日志发过来？

**Comment by JDreamLuo** [comment]
vue.runtime.esm.js?efc3:430 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by JDreamLuo** [comment]
方便加哈QQ, 帮我看看嘛，就是select.vue里面的new Vue动态创建的子组件，

**Comment by yunfeihuang** [comment]
升级vue2.3.0以上版本，可以：1136750710
